apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if .Values.service.nodeport.enabled }}
      nodePort: {{ .Values.service.nodeport.port }}
      {{- end }}
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
